general:
  kafka-topic: transactions-topic
  kafka-bootstrap-servers: localhost:9092  # 🔁 Replace with actual Kafka broker address if needed

spring:
  kafka:
    producer:
      retries: 3
      acks: all
      properties:
        linger.ms: 10
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 33400
